// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhijsbkijbdctsdlcxgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoaWpzYmtpamJkY3RzZGxjeGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1ODY0MjQsImV4cCI6MjA4NTE2MjQyNH0.sd-x4jKdgz8DZFp_dP-CYReDsYmEbXo_af1c1IVRZwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});